defaults:
  install_options: --no-rdoc --no-ri --source=http://gems.github.com --source=http://gems.rubyforge.org
gems:
- name: geminstaller
  version: 0.5.3
- name: rails
  version: 2.3.4
- name: rack
  version: 1.0.1
# - name: rubyforge # RubyForge 2.0.1 has a dependency on json, which is a native gem, which doesn't work under jruby
#   version: = 2.0.0
- name: warbler
  version: 0.9.14
# - name: jruby-jars
#   version: 1.3.1
- name: jruby-openssl
  version: 0.5.2
- name: activerecord-jdbcsqlite3-adapter
  version: 0.9.2
- name: activerecord-jdbc-adapter
  version: 0.9.2
